# Site settings
title: CRM Blog
description: 'A blog related to CRM'
url: 'https://changezkhan.github.io'
baseurl: '/crm_blog/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Sohan U. S. Tirpude'
  email: sohanworks@gmail.com
  twitter_username: ChangezKhan
  facebook_username: ChangezKhan
  github_username:  ChangezKhan
  linkedin_username:  ChangezKhan

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
